name: Deploy Next.js to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Build Next.js application
      run: pnpm run build
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        timeout: 60s
        script: |
          cd /var/www/manahilejaz.pro
          
          # Make sure we're on the right branch
          git checkout main
          
          # Pull latest changes
          git pull origin main
          
          # Install pnpm if not available
          if ! command -v pnpm &> /dev/null; then
            npm install -g pnpm
          fi
          
          # Install dependencies
          pnpm install --frozen-lockfile
          
          # Build the project
          pnpm run build
          
          # Verify out directory exists
          if [ ! -d "out" ]; then
            echo "❌ Static export failed"
            exit 1
          fi
          
          # Fix permissions for the built files
          sudo chown -R www-data:www-data /var/www/manahilejaz.pro/out/
          sudo chmod -R 755 /var/www/manahilejaz.pro/out/
          
          # Reload nginx
          sudo systemctl reload nginx || true
          
          echo "✅ Deployment completed successfully at $(date)"