name: Deploy Next.js to Server (Simple)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Build Next.js application
      run: pnpm run build
    
    - name: Verify build output
      run: |
        if [ ! -d "out" ]; then
          echo "❌ Static export failed - out directory not found"
          ls -la
          exit 1
        fi
        echo "✅ Build successful - out directory created"
        ls -la out/
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        timeout: 60s
        script: |
          cd /var/www/manahilejaz.pro
          
          # Pull latest changes
          git pull origin main
          
          # Install pnpm if not available
          if ! command -v pnpm &> /dev/null; then
            echo "Installing pnpm..."
            npm install -g pnpm
          fi
          
          
          # Install dependencies
          pnpm install --frozen-lockfile
          
          # Build the project
          pnpm run build
          
          # Verify out directory exists
          if [ ! -d "out" ]; then
            echo "❌ Static export failed on server"
            exit 1
          fi
          
          # Fix permissions for the built files
          sudo chown -R www-data:www-data /var/www/manahilejaz.pro/out/
          sudo chmod -R 755 /var/www/manahilejaz.pro/out/
          
          # Reload nginx
          sudo systemctl reload nginx || true
          
          echo "✅ Deployment completed successfully at $(date)"